### ISSUE TITLE
Can't get past "human verification" checkbox

### ISSUE THREAD

**Issue by Xeizzeth** [sonnylazuardi/chat-ai-desktop#22]
Sometimes you have to press the "verify you're human" checkbox once, sometimes even 20 times is not enough.  
Using manjaro. Installed from AUR.

**Comment by fcoury** [comment]
Same problem here.

**Comment by tesmojones** [comment]
same problem on monterey

**Comment by chrislim** [comment]
Encountering this problem right now.

**Comment by jaeyonglee8687** [comment]
Same here.
