### ISSUE TITLE
Please stand by, while we are checking your browser

### ISSUE THREAD

**Issue by Prantoe** [sonnylazuardi/chat-ai-desktop#33]
the app crashes on the verification page and then only on the "Please stand by, while we are checking your browser..." page

**Comment by YrbsAlen** [comment]
> 

thank you very much

**Comment by sonnylazuardi** [comment]
@Prantoe @YrbsAlen can you try opening https://chat.openai.com/chat in your browser first after that open the app again?

**Comment by sonnylazuardi** [comment]
Fixed with the latest release 

Download here https://github.com/sonnylazuardi/chat-ai-desktop/blob/master/releases/chatgpt.dmg
