### ISSUE TITLE
Can't get past verification box

### ISSUE THREAD

**Issue by Seba925** [sonnylazuardi/chat-ai-desktop#36]
Verification box turns solid white after a second. Can't access it, reopening and reinstalling doesn't work
Running on Windows 11 Revision os

**Comment by Seba925** [comment]
https://imgur.com/a/ypSwKCm

**Comment by sonnylazuardi** [comment]
@Seba925 just fixed in the new release, please download again https://github.com/sonnylazuardi/chat-ai-desktop#downloads
