### ISSUE TITLE
Unable to run the application on M2 MacBook, Ventura 13.2.1

### ISSUE THREAD

**Issue by bunduuk** [sonnylazuardi/chat-ai-desktop#37]
The application gives the following error ""ChatGPT" is damaged and can't be opened. You should move it to the Bin."

Current System:
Macbook Air M2
Ventura 13.2.1
<img width="261" alt="Screenshot 2023-03-19 at 1 12 57 AM" src="https://user-images.githubusercontent.com/20698396/226134007-45944ddf-5c35-4640-87f5-ba1628c1c20a.png">

**Comment by sonnylazuardi** [comment]
Fixed in this release https://github.com/sonnylazuardi/chat-ai-desktop/releases/tag/v0.4.0
